CREATE TABLE "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" varchar NOT NULL,
    "pseudo" varchar UNIQUE NOT NULL,
    "password" varchar NOT NULL,
    "id_role" integer NOT NULL
);

CREATE TABLE "role" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" enum(user, admin)
);

CREATE TABLE "challenge" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar NOT NULL,
    "description" varchar NOT NULL,
    "rules" varchar NOT NULL,
    "level" integer NOT NULL,
    "average_duration" integer NOT NULL,
    "id_user" integer NOT NULL,
    "id_game" integer NOT NULL
);

CREATE TABLE "vote_challenge" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_challenge" integer NOT NULL,
    "id_user" integer NOT NULL
);

CREATE TABLE "participation" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "video_url" varchar NOT NULL,
    "description" varchar NOT NULL,
    "duration" integer NOT NULL,
    "id_user" integer NOT NULL,
    "id_challenge" integer NOT NULL
);

CREATE TABLE "vote_participation" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_participation" integer NOT NULL,
    "id_user" integer NOT NULL
);

CREATE TABLE "game" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar NOT NULL,
    "description" varchar NOT NULL
);

COMMENT ON TABLE "challenge" IS 'Le challenge est le défis';

ALTER TABLE "user"
ADD FOREIGN KEY ("id_role") REFERENCES "role" ("id");

ALTER TABLE "challenge"
ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "challenge"
ADD FOREIGN KEY ("id_game") REFERENCES "game" ("id");

ALTER TABLE "participation"
ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "participation"
ADD FOREIGN KEY ("id_challenge") REFERENCES "challenge" ("id");

ALTER TABLE "vote_participation"
ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "vote_participation"
ADD FOREIGN KEY ("id_participation") REFERENCES "participation" ("id");

ALTER TABLE "vote_challenge"
ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "vote_challenge"
ADD FOREIGN KEY ("id_challenge") REFERENCES "challenge" ("id");