CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "pseudo" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "password" varchar NOT NULL,
  "address" varchar,
  "urlChannel" varchar,
  "id_role" integer NOT NULL
);

CREATE TABLE "role" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" enum(user,admin)
);

CREATE TABLE "challenge" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "rules" varchar NOT NULL,
  "level" integer NOT NULL,
  "reference_duration" integer NOT NULL,
  "id_user" integer NOT NULL,
  "id_game" integer NOT NULL
);

CREATE TABLE "vote_challenge" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" integer NOT NULL,
  "id_challenge" integer NOT NULL
);

CREATE TABLE "participation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "duration" integer NOT NULL,
  "video_url" varchar NOT NULL,
  "id_user" integer NOT NULL,
  "id_challenge" integer NOT NULL
);

CREATE TABLE "vote_participation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" integer NOT NULL,
  "id_participation" integer NOT NULL
);

CREATE TABLE "game" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "category" varchar NOT NULL,
  "description" varchar NOT NULL
);

COMMENT ON TABLE "challenge" IS 'Le challenge est le défi';

ALTER TABLE "user" ADD FOREIGN KEY ("id_role") REFERENCES "role" ("id");

ALTER TABLE "challenge" ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "challenge" ADD FOREIGN KEY ("id_game") REFERENCES "game" ("id");

ALTER TABLE "participation" ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "participation" ADD FOREIGN KEY ("id_challenge") REFERENCES "challenge" ("id");

ALTER TABLE "vote_participation" ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "vote_participation" ADD FOREIGN KEY ("id_participation") REFERENCES "participation" ("id");

ALTER TABLE "vote_challenge" ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "vote_challenge" ADD FOREIGN KEY ("id_challenge") REFERENCES "challenge" ("id");
