services:
  # 1. Base de données
  db:
    image: postgres:17-alpine
    container_name: gamerChallenges_db
    restart: always
    profiles:
      - dev
      - prod
    env_file:
      - .database.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend (API)
  api:
    build: ./api
    container_name: gamerChallenges_api
    ports:
      - "3000:3000"
    profiles:
      - dev
    env_file:
      - .database.env
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  # 3. Frontend (Client) - mode développement
  client:
    # Le Dockerfile est dans client/myapp selon ton arborescence
    build: ./client/myapp
    container_name: gamerChallenges_client
    ports:
      - "5173:5173"
    profiles:
      - dev
    volumes:
      - ./client/myapp:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
    # Commande pour lancer le serveur de dev Vite/Svelte en mode exposé
    command: npm run dev -- --host

  # 4. Backend (API) - mode production
  api-prod:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: gamerChallenges_api_prod
    profiles:
      - prod
    env_file:
      - .database.env
      - api/.env.prod
    restart: unless-stopped
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # 5. Frontend + reverse proxy Nginx - mode production
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: gamerChallenges_nginx
    profiles:
      - prod
    depends_on:
      - api-prod
    ports:
      - "80:80"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  postgres_data: